server:
    port: 8082
    servlet:
        context-path: '/dl-course/' # This is the context path for the service. Used in conjunction with the API Gateway that has it mapped in the routes.

spring:
    application:
        name: dl-course-service
    datasource:
        url: jdbc:postgresql://localhost:5432/dl-course
        username: postgres
        password: root
    jpa:
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.PostgreSQLDialect
            jdbc:
                lob.non_contextual_creation: true
#        show-sql: true
#        properties:
#            hibernate:
#                format_sql: true
#                show_sql: true

logging:
    level:
        com.xpto.distancelearning: TRACE
        root: INFO
        org.springframework.web: DEBUG
        org.hibernate: INFO

distance-learning:
    api:
        url:
#            authuser: 'http://localhost:8087'# I do not to hardcode the URL anymore and instead use the service name defined in the Eureka.
            authuser: 'http://dl-authuser-service/dl-authuser'

eureka:
    client:
        service-url:
            defaultZone: 'http://localhost:8761/eureka'
    instance:
        hostname: localhost